name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_SYSTEM_PYTHON: true

jobs:
  lint:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false

      - uses: astral-sh/setup-uv@v6

      - name: Ruff (lint)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: ruff-check --all-files

      - name: Ruff (format)
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: ruff-format --all-files

      - name: Blacken-docs
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: blacken-docs --all-files

      - name: mdformat
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: mdformat --all-files

      - name: actionlint
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: actionlint --all-files

      - name: validate-pyproject
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: validate-pyproject --all-files

      - name: yamlfmt
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: yamlfmt --all-files

  mypy:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v6

      - name: Install package with all extras
        run: uv pip install -e .[doc,lint,test] mypy

      - name: Run mypy
        run: mypy ./src
